zombit_otea_userspage:
    resource: "@ZombitOteaBundle/Resources/config/routing/user.yml"
    prefix:   /users

zombit_otea_homepage:
    path:     /
    defaults: { _controller: FOSUserBundle:Security:login }

zombit_otea_dashboardpage:
    path:     /dashboard
    defaults: { _controller: ZombitOteaBundle:Default:dashboard }

zombit_otea_searchpage:
    path:     /search
    defaults: { _controller: ZombitOteaBundle:Default:search }